services:
  outline:
    container_name: outline
    image: docker.getoutline.com/outlinewiki/outline:latest
    env_file:
      - path: ./outline.env
    ports:
      - "3000:3000" # OUTLINE PORT
    volumes:
      - ./easy-outline/storage-data:/var/lib/outline/data
    depends_on:
      - postgres
      - redis
      - api

  redis:
    container_name: redis-outline
    image: redis
    volumes:
      - ./easy-outline/redis.conf:/redis.conf
    env_file:
      - path: ./outline.env
    ports:
      - "6379:6379" # REDIS PORT
    command: ["redis-server", "/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 3

  postgres:
    container_name: postgres-outline
    restart: always
    image: postgres
    env_file:
      - path: ./outline.env
    ports:
      - "5432:5432" # POSTGRES PORT
    volumes:
      - ./easy-outline/database-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "outline", "-U", "user"]
      interval: 30s
      timeout: 20s
      retries: 3

  api:
    build:
      context: ./easy-outline/iframely/
      dockerfile: Dockerfile
    container_name: iframely-outline
    volumes:
      - ./easy-outline/iframely/config.local.js:/iframely/config.local.js
    restart: always
    ports:
      - "8061:8061" # IFRAMELY PORT <<< TODO
